### ISSUE TITLE
Can't use raw command for getting params

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-cli#2]
https://github.com/jataware/dojo-cli/blob/feature/rtk-dev-issues/dojocli/cli.py#L117-L135 this code breaks for `AgMIP Seasonal Crop Emulator` explicitly and `Flee Model for South Sudan, 2013 to 2015` silently because their raw commands don't necessarily have the parameters.

I think we should just suck the parameters out of the `model` metadata which will include their default values.

Is there some value to looking at the `raw command` that I might be missing?

**Comment by GoogleSheets** [comment]
Changed to getting params and default values from the `model` metadata.
